spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jwt_security
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver # tell hibernate, this project use thid class for connecting to database
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true # show sql script when query
        properties:
            hibernate:
                '[format_sql]': true # format sql for easy to read
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect # tell hibernate, this project use mysql version 8